In [24]:
import tensorflow as tf
import tensorflow.keras as keras

import numpy as np
import pandas as pd

In [2]:
model = keras.models.load_model('models/ar_10k.h5')

In [3]:
weights = tf.Variable(model.layers[0].get_weights()[0])

In [4]:
weights.shape

TensorShape([10002, 300])

In [5]:
checkpoint = tf.train.Checkpoint(embedding=weights)

In [6]:
checkpoint.save("logs/embedding_10k_ar.ckpt")

'logs/embedding_10k_ar.ckpt-1'

In [7]:
from tensorboard.plugins import projector

In [8]:
config = projector.ProjectorConfig()
embedding = config.embeddings.add()

In [9]:
embedding.tensor_name = "embedding_10k_ar/.ATTRIBUTES/VARIABLE_VALUE"
embedding.metadata_path = 'metadata_ar_10k.tsv'
projector.visualize_embeddings('logs/', config)

In [11]:
words = pd.read_csv('logs/metadata_ar_10k.tsv', names=['token'])

In [50]:
embeddings = {}
weights = np.array(weights)
for word, embeds in zip(words['token'], weights):
    embeddings[word] = embeds

In [51]:
embeddings['الي'][:10]

array([ 0.27407244, -0.8177569 , -0.04993073,  0.3334608 , -0.34902954,
       -0.39792967,  0.22859468, -0.15345533, -0.00472249, -0.8078031 ],
      dtype=float32)

In [56]:
import pickle

In [57]:
def save_obj(obj, name ):
    with open(name + '.pkl', 'wb') as f:
        pickle.dump(obj, f, pickle.HIGHEST_PROTOCOL)

def load_obj(name ):
    with open(name + '.pkl', 'rb') as f:
        return pickle.load(f)

In [58]:
save_obj(embeddings, 'pretrained_ar')

In [59]:
embeddings = load_obj('pretrained_ar')

In [60]:
embeddings['الي'][:10]

array([ 0.27407244, -0.8177569 , -0.04993073,  0.3334608 , -0.34902954,
       -0.39792967,  0.22859468, -0.15345533, -0.00472249, -0.8078031 ],
      dtype=float32)

In [62]:
en_model =  keras.models.load_model('models/en_10k_kaggle.h5')

In [63]:
weights = tf.Variable(model.layers[0].get_weights()[0])

In [64]:
words = pd.read_csv('logs/metadata_10k.tsv', names=['token'])

In [66]:
embeddings = {}
weights = np.array(weights)
for word, embeds in zip(words['token'], weights):
    embeddings[word] = embeds

In [68]:
embeddings['the'][:10]

array([ 0.34345427,  0.16130535, -0.21006979, -0.02174319,  0.11983871,
        0.12045165,  0.43488872, -0.10986105,  0.17680338, -0.38824806],
      dtype=float32)

In [69]:
save_obj(embeddings, 'pretrained_en')

In [70]:
embeddings = load_obj('pretrained_en')

In [71]:
embeddings['the'][:10]

array([ 0.34345427,  0.16130535, -0.21006979, -0.02174319,  0.11983871,
        0.12045165,  0.43488872, -0.10986105,  0.17680338, -0.38824806],
      dtype=float32)